# Generated by Django 3.2.9 on 2021-11-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyhistory',
            old_name='img_urg',
            new_name='img_url',
        ),
        migrations.AlterField(
            model_name='companyhistory',
            name='description',
            field=models.TextField(),
        ),
    ]
